"""
LLM Provider Abstraction Layer

Supports:
  1. MockProvider  – deterministic, no API key needed, always works locally
  2. Future: OpenAIProvider, AnthropicProvider, GoogleProvider, etc.

The active provider is selected based on environment variables.
If no LLM API key is configured, the system falls back to MockProvider
and clearly labels responses as "MOCK / DETERMINISTIC".
"""

from abc import ABC, abstractmethod
from typing import List, Dict, Any, Optional
import os
import re


class LLMProvider(ABC):
    """Abstract base class for LLM providers."""

    @abstractmethod
    def generate(self, system_prompt: str, user_prompt: str) -> str:
        """Generate a text response given system and user prompts."""
        ...

    @abstractmethod
    def provider_name(self) -> str:
        """Human-readable provider name for citation metadata."""
        ...

    @abstractmethod
    def is_mock(self) -> bool:
        """Whether this provider generates deterministic/mock responses."""
        ...


class MockProvider(LLMProvider):
    """
    Deterministic mock provider that generates structured answers
    directly from the context provided in the prompt.
    No external API calls. Always available.
    """

    def provider_name(self) -> str:
        return "NWIS Deterministic Engine (Mock – No LLM API Key Configured)"

    def is_mock(self) -> bool:
        return True

    def generate(self, system_prompt: str, user_prompt: str) -> str:
        """
        Parse the structured context embedded in the user_prompt and
        produce a deterministic summary. This is NOT an LLM – it is a
        template-based formatter that faithfully reflects the data.
        """
        # The RAG service embeds structured context in a known format.
        # We parse that and format a response.
        return self._format_from_context(user_prompt)

    def _format_from_context(self, prompt: str) -> str:
        """Extract the CONTEXT block and USER QUESTION, then template a response."""
        # Split context from question
        context_match = re.search(
            r"--- HISTORICAL EVIDENCE ---\n(.*?)\n--- END EVIDENCE ---",
            prompt, re.DOTALL
        )
        question_match = re.search(
            r"--- USER QUESTION ---\n(.*?)$",
            prompt, re.DOTALL
        )

        context = context_match.group(1).strip() if context_match else ""
        question = question_match.group(1).strip() if question_match else prompt.strip()

        if not context:
            return (
                "No supporting historical evidence was found in the current dataset "
                "for this query. Please try a different search term, depth range, "
                "or formation name."
            )

        # Build a deterministic summary from context lines
        lines = context.strip().split("\n")
        summary_parts = []
        current_section = None

        for line in lines:
            line = line.strip()
            if not line:
                continue
            if line.startswith("[EVENT"):
                current_section = line
                summary_parts.append(f"\n{line}")
            elif line.startswith("- "):
                summary_parts.append(line)

        if not summary_parts:
            return (
                "Historical records were found but could not be summarised. "
                "Please review the source evidence directly."
            )

        wells_cited = set()
        for line in lines:
            if line.startswith("- Well:"):
                w = line.replace("- Well:", "").split("(")[0].strip()
                wells_cited.add(w)

        return (
            f"**Answer**: Based on historical drilling records, similar events occurred in offset wells near this depth.\n\n"
            f"**Supporting wells**: {', '.join(wells_cited) if wells_cited else 'Multiple offset wells'}\n\n"
            f"**Depths**: Extracted from recorded intervals.\n\n"
            f"**Event details**:\n"
            + "\n".join(summary_parts)
            + f"\n\n**Source documents**: Reference Final Well Reports (FWR) for cited wells.\n\n"
            f"*(Note: Historical reports show mitigations used during similar events. The engineer remains responsible for the decision.)*\n\n"
            f"⚠ This response was generated by the NWIS deterministic engine (no LLM API key configured)."
        )


def get_provider() -> LLMProvider:
    """
    Factory: return the appropriate LLM provider based on env vars.
    Falls back to MockProvider if no key is set.
    """
    api_key = os.getenv("LLM_API_KEY", "")
    provider_type = os.getenv("LLM_PROVIDER", "mock").lower()

    if api_key and provider_type == "openai":
        pass
    if api_key and provider_type == "anthropic":
        pass
    if api_key and provider_type == "google":
        pass

    return MockProvider()
